services:
  nomad:
    image: ncode/cni-output:dev 
    ports:
      - "4646:4646"  # HTTP API
      - "4647:4647"  # RPC
      - "4648:4648"  # Serf WAN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M
        reservations:
          cpus: 2
          memory: 512M

networks:
  default:
    driver: bridge
